# Generated by Django 4.2.3 on 2023-07-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Student',
        ),
    ]
