# Generated by Django 4.2.3 on 2023-07-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_rename_review_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Review',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
