# Generated by Django 4.2.3 on 2023-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_rename_student_review_delete_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_avg_city', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
